version: '3'

tasks:
  default:
    cmds:
      - task: deploy
  build:
    cmds:
      - go build -o bin/task
  deploy:
    deps: [build]
    cmds:
      - scp bin/task ssh student@roivioli-server.eddi.cloud:/home/student/
      - ssh ssh student@roivioli-server.eddi.cloud "chmod u+x task"